version: '3'
services:
  mydb:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    #restart: always
    ports:
     - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: srstee
      MYSQL_DATABASE: srstee
      MYSQL_USER: proxyuser
      MYSQL_PASSWORD: srstee      
  impex2:    
    depends_on:    
      - mydb
    image: srste/srste:2.0.0
    command: node --max-old-space-size=6144 server/server.js --single
    #command: npm run debug
    #command: node -e 'setTimeout(()=>console.log("Test!"), 10000000)' 
    environment:
      - NODE_ENV=production
      - NODE_ID=Node1      
      - NODE_OPTIONS="--max-old-space-size=10240"
      - DB_USER=proxyuser
      - DB_PORT=3307
      - DB_HOST=192.168.0.101
      - DB_PASSWORD=srstee
      - DB_DATABASE=srstee
      - REDIS=192.168.0.101:6379
      - TESTRUN_URL=localhost
      - USE_REDIS=true      
      - WORKFLOW_URL=http://185.162.124.49:8091
    ports:
     - "8012:8080"  
     - "9229:9229"  
     - "2224:2222"  
     - "1337:1337"
     - "1338:1338"     
    restart: always
volumes:
    db_data:
