FROM node:10-alpine
#FROM node:10-alpine
#RUN apk --no-cache add git
#RUN apk --no-cache add python
# Create app directory
WORKDIR /app/srstee_prod

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ./dest /app/srstee_prod

WORKDIR /app/srstee_prod
RUN rm -rf node_modules
RUN npm cache clean --force

RUN npm install jspm@beta -g
RUN npm install loopback -g
RUN npm install node-gyp -g

#RUN npm install grunt-cli

WORKDIR /app/srstee_prod/client
#RUN npm install

RUN jspm config maxRetries 50000
RUN jspm config registries.npm.timeouts.lookup 1000

#RUN jspm install --dev

#Obfuscation
WORKDIR /app/srstee_prod/mmf/base
RUN npm install javascript-obfuscator -g
RUN javascript-obfuscator ./script --output ./dist
RUN rm -rf ./script
RUN mv ./dist/script ./script
RUN rm -rf ./dist

WORKDIR /app/srstee_prod
RUN pwd
EXPOSE 8080
CMD [ "npm", "start" ]
